"""aiopikvm — async Python client for PiKVM API."""

from aiopikvm._client import PiKVM
from aiopikvm._exceptions import (
    APIError,
    AuthError,
    BusyError,
    ConfigurationError,
    ConnectError,
    ConnectionTimeoutError,
    PiKVMError,
    RedirectError,
    ResponseError,
    UnavailableError,
    WebSocketError,
)
from aiopikvm._ws import PiKVMWebSocket
from aiopikvm.models.atx import ATXLeds, ATXState
from aiopikvm.models.gpio import GPIOChannel, GPIOInput, GPIOState
from aiopikvm.models.hid import (
    HIDJiggler,
    HIDKeyboard,
    HIDKeyboardLeds,
    HIDKeymaps,
    HIDMouse,
    HIDOutputs,
    HIDState,
)
from aiopikvm.models.msd import (
    MSDDownload,
    MSDDrive,
    MSDDriveImage,
    MSDImage,
    MSDPart,
    MSDState,
    MSDStorage,
    MSDUpload,
)
from aiopikvm.models.streamer import (
    OCRInfo,
    OCRLangs,
    Resolution,
    Streamer,
    StreamerEncoder,
    StreamerFeatures,
    StreamerH264,
    StreamerLimitRange,
    StreamerLimits,
    StreamerParams,
    StreamerSinkInfo,
    StreamerSinks,
    StreamerSnapshot,
    StreamerSource,
    StreamerState,
    StreamerStream,
)
from aiopikvm.models.switch import EDID, SwitchPort, SwitchState

__version__ = "0.2.1"

__all__ = [
    "EDID",
    "APIError",
    "ATXLeds",
    "ATXState",
    "AuthError",
    "BusyError",
    "ConfigurationError",
    "ConnectError",
    "ConnectionTimeoutError",
    "GPIOChannel",
    "GPIOInput",
    "GPIOState",
    "HIDJiggler",
    "HIDKeyboard",
    "HIDKeyboardLeds",
    "HIDKeymaps",
    "HIDMouse",
    "HIDOutputs",
    "HIDState",
    "MSDDownload",
    "MSDDrive",
    "MSDDriveImage",
    "MSDImage",
    "MSDPart",
    "MSDState",
    "MSDStorage",
    "MSDUpload",
    "OCRInfo",
    "OCRLangs",
    "PiKVM",
    "PiKVMError",
    "PiKVMWebSocket",
    "RedirectError",
    "Resolution",
    "ResponseError",
    "Streamer",
    "StreamerEncoder",
    "StreamerFeatures",
    "StreamerH264",
    "StreamerLimitRange",
    "StreamerLimits",
    "StreamerParams",
    "StreamerSinkInfo",
    "StreamerSinks",
    "StreamerSnapshot",
    "StreamerSource",
    "StreamerState",
    "StreamerStream",
    "SwitchPort",
    "SwitchState",
    "UnavailableError",
    "WebSocketError",
    "__version__",
]
